### ISSUE TITLE
Upgrade to JUnit 5

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#254]
JUnit 5 is out and it looks like there's a bunch of new stuff!

https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4

It's not immediately clear to me how much of my source code I will have to change to get it to work with JUnit 5.  It sounds like Jupiter changes a lot.

https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven

**Comment by michaelheyman** [comment]
While upgrading to JUnit5, running `mvn test` was showing the following:

```

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```

There is a documented fix for this.

https://dzone.com/articles/why-your-junit-5-tests-are-not-running-under-maven

The simple fix that worked for me was to downgrading the version of `maven-surefire-plugin` and adding dependencies:

```maven
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.19.1</version>
    <dependencies>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-surefire-provider</artifactId>
            <version>1.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.1.0</version>
        </dependency>
    </dependencies>
</plugin>
```

The link mentioned above recommends updating maven instead of this approach, but I had no success there.

**Comment by DavidWhitlock** [comment]
Ooh.  There's lots of cool stuff in JUnit 5.  I'll need to create some new lecture content in order to explain it all.  This video was helpful: https://dzone.com/articles/whats-new-in-junit-5-video?fromrel=true

**Comment by DavidWhitlock** [comment]
The Maven surefire plugin's support for JUnit 5 is improving in plugin version 3.0.0: https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit-platform.html  
Looks like they are still working on milestones.
I supposed I could see what would happen if upgraded the surefire plugin and ran the JUnit 4.X tests.

**Comment by DavidWhitlock** [comment]
Another good source for JUnit 5: https://www.baeldung.com/junit-5-migration

**Comment by DavidWhitlock** [comment]
Okay.  JUnit 5 is pretty cool, but there's a lot of stuff that most students won't need to use.  I should probably:
   * Update the code to use the Jupiter APIs
   * Update the `junit` slides to discuss these APIs
   * Consider a new "JUnit 5 Deep Dive" slide deck to discuss all of the cool stuff in JUnit 5

**Comment by DavidWhitlock** [comment]
What do I need to do to migrate the source code to use JUnit 5?
  - [ ] Replace the `junit` dependencies in Maven POM file with `jupiter`
  - [ ] Replace usage of the `org.junit` APIs with `org.junit.jupiter.api`
  - [ ] Make the visibility of test classes and test methods `default` instead of `public`
  - [ ] Replace `@FixMethodOrder` with `@TestMethodOrder(MethodName.class)`

**Comment by DavidWhitlock** [comment]
Travis builds were failing with this.  I likely have to update the dependencies Maven plug in.

```
[INFO] org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 19
[INFO]     at org.apache.bcel.classfile.Constant.readConstant (Constant.java:146)
[INFO]     at org.apache.bcel.classfile.ConstantPool.<init> (ConstantPool.java:67)
[INFO]     at org.apache.bcel.classfile.ClassParser.readConstantPool (ClassParser.java:222)
[INFO]     at org.apache.bcel.classfile.ClassParser.parse (ClassParser.java:136)
[INFO]     at org.apache.maven.shared.jar.classes.JarClassesAnalysis.analyze (JarClassesAnalysis.java:92)
[INFO]     at org.apache.maven.report.projectinfo.dependencies.Dependencies.getJarDependencyDetails (Dependencies.java:259)
[INFO]     at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.hasSealed (DependenciesRenderer.java:1517)
[INFO]     at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails (DependenciesRenderer.java:535)
[INFO]     at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody (DependenciesRenderer.java:258)
[INFO]     at org.apache.maven.reporting.AbstractMavenReportRenderer.render (AbstractMavenReportRenderer.java:83)
[INFO]     at org.apache.maven.report.projectinfo.DependenciesReport.executeReport (DependenciesReport.java:201)
[INFO]     at org.apache.maven.reporting.AbstractMavenReport.generate (AbstractMavenReport.java:255)
[INFO]     at org.apache.maven.plugins.site.render.ReportDocumentRenderer.renderDocument (ReportDocumentRenderer.java:230)
[INFO]     at org.apache.maven.doxia.siterenderer.DefaultSiteRenderer.render (DefaultSiteRenderer.java:349)
[INFO]     at org.apache.maven.plugins.site.render.SiteMojo.renderLocale (SiteMojo.java:198)
[INFO]     at org.apache.maven.plugins.site.render.SiteMojo.execute (SiteMojo.java:147)
```

**Comment by DavidWhitlock** [comment]
Oh.  This is probably why the Travis job failed:

```
The job exceeded the maximum log length, and has been terminated.
```
