### ISSUE TITLE
Stop generating the "Dependency Reduced POM"

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#259]
The way the Maven shade plugin is currently configured, running the plugin creates a `dependency-reduced-pom.xml` in the ${basedir}.  This is annoying and caches some stuff that shouldn't be cached.

I think we can remove it by setting this property of the shade plugin to `false`

https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#createDependencyReducedPom

**Comment by michaelheyman** [comment]
I can confirm that setting the property disables the creation of the file.

The following plugin configuration works:

```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-shade-plugin</artifactId>
    <version>2.2</version>
    <configuration>
        <createDependencyReducedPom>false</createDependencyReducedPom>
    </configuration>
    ...
</plugin>
```

**Comment by DavidWhitlock** [comment]
Changes to address this issue have been merged to `master` and deployed to bintray.
