### ISSUE TITLE
Add pom support for com.google.common.annotations

### ISSUE THREAD

**Issue by michaelheyman** [DavidWhitlock/PortlandStateJava#262]
Currently the pom doesn't support `com.google.common.annotations`. These annotations have useful utilities, such as the `VisibleForTesting` annotation.

**Comment by DavidWhitlock** [comment]
Oh, interesting.  I noticed that a class like `AirlineServlet` created by a project archetype can use `VisibleForTesting`.  It gets that class from the `guava` library, which is a transitive dependency from the `examples` jar.  I can make the annotations (or maybe just `guava`) dependency a first-class citizen.

**Comment by DavidWhitlock** [comment]
Oh.  And I had another student who wanted to use `@VisibleForTesting` in their code.  The command line projects don't appear to have the `guava` library as a transitive dependency.  I should add the dependency to the projects.

**Comment by DavidWhitlock** [comment]
And I should add `mockito` to the command line project dependencies, as well.  Why, not?

**Comment by DavidWhitlock** [comment]
And mockito support is captured in #309

**Comment by DavidWhitlock** [comment]
I think the changes for #309 also address this issue.
