### ISSUE TITLE
Use java.time objects for the projects

### ISSUE THREAD

**Issue by DavidWhitlock** [DavidWhitlock/PortlandStateJava#264]
The `Date` and `SimpleDateFormat` classes are old and there is a lot of deprecated functionality.  In Project 3, students are finding that the date parsing isn't strict enough, which is leading to a lot of confusion.  I should explore replacing `Date` in the abstract application classes with something form the `java.time` package.

**Comment by abluescarab** [comment]
Hi David, I've messed around a bit with `ZonedDateTime` over in [my repository](https://github.com/abluescarab/psu-cs/blob/cs410p-advprogramminginjava/CS410P-advprogramminginjava/phonebill/src/main/java/edu/pdx/cs410J/agilston/PhoneCall.java). I initially used `LocalDateTime` but found that it defaulted to a timezone that did not print correctly, so I changed to `ZonedDateTime`.
